### ISSUE TITLE
Hotkey Ctrl+Alt+5 registered

### ISSUE THREAD

**Issue by thany** [AlanHohn/markdown-toolbar#1]
This extension registers the Ctrl+Alt+5 hotkey, which in Windows is already mapped to the €-sign on most keyboard layouts. Currently the result is that the €-sign doesn't always appear when using Ctrl+Alt+5 even in files other than markdown.

I've [filed a bug](https://github.com/adobe/brackets/issues/12626) for Brackets about this. The reason I'm filing it here as well, is because it's a bad idea to (try to) overwrite Ctrl+Alt+5 for most EU Windows users, or those who otherwise deal with euros.

**Comment by AlanHohn** [comment]
Thanks for writing this up for me. I've removed the keyboard shortcuts for H5 and H6; since they're probably not used that often this seemed the best solution.

I released 1.1.3 with this change.
