### ISSUE TITLE
Links and images

### ISSUE THREAD

**Issue by raphaelgoetter** [AlanHohn/markdown-toolbar#2]
Hello,

I really love this extension.

Is it possible to add two of the most used features ? 
- add a link 
- add img placeholder

Have a nice day,

Raphaël

**Comment by AlanHohn** [comment]
Raphaël,

Thanks! Yes, that does seem like a very useful pair of features.

I've released 1.2.0 with image and link buttons.

**Comment by raphaelgoetter** [comment]
Great, thank you !
